# Generated by Django 4.2.9 on 2024-01-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Object_Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, db_column="Name", max_length=30, unique=True
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, db_column="Description", max_length=200, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Object_Unit_Create",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, db_column="Name", max_length=30)),
                (
                    "version",
                    models.CharField(
                        blank=True, db_column="Version", max_length=30, null=True
                    ),
                ),
                (
                    "homepage",
                    models.CharField(
                        blank=True, db_column="Homepage", max_length=200, null=True
                    ),
                ),
                (
                    "mitre_name",
                    models.CharField(
                        blank=True, db_column="MITRE_Name", max_length=30, null=True
                    ),
                ),
                (
                    "mitre_version",
                    models.CharField(
                        blank=True, db_column="MITRE_Version", max_length=30, null=True
                    ),
                ),
                (
                    "vendor",
                    models.CharField(
                        blank=True, db_column="Vendor", max_length=100, null=True
                    ),
                ),
                (
                    "cpe",
                    models.CharField(
                        blank=True, db_column="CPE", max_length=200, null=True
                    ),
                ),
            ],
        ),
    ]
