# Generated by Django 4.2.9 on 2024-01-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BOM_Dictionary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bom_component",
                    models.CharField(
                        db_column="BOMComponent", max_length=200, null=True
                    ),
                ),
                (
                    "bom_component_version",
                    models.CharField(
                        db_column="BOMComponentVersion", max_length=200, null=True
                    ),
                ),
                (
                    "bom_homepage",
                    models.CharField(
                        db_column="BOMHomepage", max_length=200, null=True
                    ),
                ),
                (
                    "component",
                    models.CharField(db_column="Component", max_length=200, null=True),
                ),
                (
                    "version",
                    models.CharField(db_column="Version", max_length=200, null=True),
                ),
                (
                    "vendor",
                    models.CharField(db_column="Vendor", max_length=200, null=True),
                ),
                ("cpe", models.CharField(db_column="CPE", max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Object_Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, db_column="Name", max_length=30, unique=True
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, db_column="Description", max_length=200, null=True
                    ),
                ),
            ],
        ),
    ]
