# Generated by Django 4.2.9 on 2024-01-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bwt2024", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Object_Unit_Download",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "component",
                    models.CharField(
                        blank=True, db_column="Component", max_length=200, unique=True
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True, db_column="Version", max_length=200, null=True
                    ),
                ),
            ],
        ),
    ]
